"""Demonstration sources and conversion to the frozen Actsemble schema.

Phase 0 uses the official ManiSkill demonstration bundles. The PushT-v1
demos were generated by an RL policy in 1024 parallel physx_cuda
environments; GPU PhysX dynamics are batch-size dependent, so ACTION
replay in a single env does not reproduce them (verified: ~1/8 episodes
stay successful). We therefore export via STATE PROJECTION: every recorded
env state is set in the simulator and the state observation is computed
from it, yielding exactly the recorded (s_t, a_t, s_{t+1}) transitions.
Success at the final state is re-evaluated with the task's own state-based
success function, so exported episodes are successful by construction.

Recorded actions are clipped to the controller's action-space bounds
before export: the controller clips internally at execution time, so the
clipped action is the command that actually produced s_{t+1}.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Protocol

import h5py
import numpy as np

from ..types import EpisodeRecord
from .env_factory import env_contract, verify_env_matches
from .observation_adapter import to_numpy_state


@dataclass
class RawDemonstration:
    source_episode_id: str
    episode_seed: int
    actions: np.ndarray  # [T, A] as recorded (pre-clipping)
    env_states: list[dict]  # T+1 nested state dicts
    source_success: bool


class DemonstrationSource(Protocol):
    def episodes(self) -> Iterator[RawDemonstration]: ...

    def describe(self) -> dict: ...

    @property
    def env_info(self) -> dict: ...


class ManiSkillTrajectorySource:
    """Official ManiSkill trajectory bundle (.h5 + .json).

    ``subset_size``/``subset_seed`` select a deterministic NESTED subset
    (protocol §7): one seeded permutation of all source episodes is drawn,
    and subset n is its first n entries — so any smaller subset with the
    same seed is contained in every larger one. The chosen keys (the
    subset manifest) are exposed via ``subset_manifest()``.
    """

    def __init__(
        self,
        traj_path: str | Path,
        *,
        max_episodes: int | None = None,
        subset_size: int | None = None,
        subset_seed: int = 0,
    ):
        self.h5_path = Path(traj_path)
        self.json_path = self.h5_path.with_suffix(".json")
        if not self.h5_path.exists() or not self.json_path.exists():
            raise FileNotFoundError(
                f"Trajectory bundle incomplete: {self.h5_path} / {self.json_path}. "
                f"Download with: python -m mani_skill.utils.download_demo <task_id>"
            )
        with open(self.json_path) as f:
            self._meta = json.load(f)
        self._episode_meta = {e["episode_id"]: e for e in self._meta["episodes"]}
        self.max_episodes = max_episodes
        self.subset_size = subset_size
        self.subset_seed = int(subset_seed)

    @property
    def env_info(self) -> dict:
        return self._meta["env_info"]

    def _all_keys(self) -> list[str]:
        with h5py.File(self.h5_path, "r") as f:
            return sorted(f.keys(), key=lambda k: int(k.split("_")[1]))

    def selected_keys(self) -> list[str]:
        keys = self._all_keys()
        if self.subset_size is not None:
            perm = np.random.default_rng(self.subset_seed).permutation(len(keys))
            chosen = {keys[i] for i in perm[: self.subset_size]}
            keys = [k for k in keys if k in chosen]  # stable original order
        if self.max_episodes is not None:
            keys = keys[: self.max_episodes]
        return keys

    def subset_manifest(self) -> dict:
        return {
            "subset_size": self.subset_size,
            "subset_seed": self.subset_seed,
            "max_episodes": self.max_episodes,
            "selected_source_episodes": self.selected_keys(),
            "nesting": "first-n of one seeded permutation (nested across sizes)",
        }

    def describe(self) -> dict:
        return {
            "kind": "maniskill_trajectory_bundle",
            "h5_path": str(self.h5_path),
            "json_path": str(self.json_path),
            "source_type": self._meta.get("source_type"),
            "source_desc": self._meta.get("source_desc"),
            "env_info": self.env_info,
            "total_source_episodes": len(self._episode_meta),
            "subset": self.subset_manifest(),
        }

    def episodes(self) -> Iterator[RawDemonstration]:
        from mani_skill.trajectory import utils as traj_utils

        with h5py.File(self.h5_path, "r") as f:
            keys = self.selected_keys()
            for key in keys:
                ep_meta = self._episode_meta[int(key.split("_")[1])]
                group = f[key]
                yield RawDemonstration(
                    source_episode_id=key,
                    episode_seed=int(ep_meta["episode_seed"]),
                    actions=np.asarray(group["actions"], dtype=np.float32),
                    env_states=traj_utils.dict_to_list_of_dicts(group["env_states"]),
                    source_success=bool(ep_meta.get("success", False)),
                )


def convert_demonstrations(
    source: DemonstrationSource,
    env,
    *,
    require_success_at_end: bool = True,
) -> tuple[list[EpisodeRecord], dict]:
    """State-projection conversion of raw demos to EpisodeRecords.

    The env must already match the source bundle (verified here — fails
    loudly on controller/backend mismatch).
    """
    src_env_kwargs = source.env_info.get("env_kwargs", {})
    verify_env_matches(
        env,
        {
            "task_id": source.env_info.get("env_id"),
            "controller": src_env_kwargs.get("control_mode"),
            "simulation_backend": src_env_kwargs.get("sim_backend"),
        },
        what="demonstration conversion",
    )
    u = env.unwrapped
    contract = env_contract(env)
    low, high = contract["action_low"], contract["action_high"]

    episodes: list[EpisodeRecord] = []
    exported, rejected, failures = [], [], []
    for demo in source.episodes():
        try:
            T = demo.actions.shape[0]
            if len(demo.env_states) != T + 1:
                raise ValueError(
                    f"{demo.source_episode_id}: {len(demo.env_states)} states for {T} actions"
                )
            env.reset(seed=demo.episode_seed)
            states = np.empty((T + 1, contract_state_dim(env)), dtype=np.float32)
            for t, env_state in enumerate(demo.env_states):
                u.set_state_dict(env_state)
                states[t] = to_numpy_state(u.get_obs())
            final_info = u.get_info()
            success_at_end = bool(final_info["success"].item())
            if require_success_at_end and not success_at_end:
                rejected.append(
                    {
                        "source_episode_id": demo.source_episode_id,
                        "reason": "not successful at final state",
                    }
                )
                continue
            actions = np.clip(demo.actions, low, high).astype(np.float32)
            previous = np.concatenate(
                [np.zeros((1, actions.shape[1]), np.float32), actions[:-1]]
            )
            episode_id = f"ep_{len(episodes):05d}"
            episodes.append(
                EpisodeRecord(
                    episode_id=episode_id,
                    state=states[:-1],
                    previous_action=previous,
                    action=actions,
                    next_state=states[1:],
                    step_index=np.arange(T, dtype=np.int64),
                )
            )
            exported.append(
                {
                    "episode_id": episode_id,
                    "source_episode_id": demo.source_episode_id,
                    "source_episode_seed": demo.episode_seed,
                    "source_success": demo.source_success,
                    "projected_success_at_end": success_at_end,
                    "length": T,
                }
            )
        except Exception as exc:
            failures.append(
                {"source_episode_id": demo.source_episode_id, "error": repr(exc)}
            )

    provenance = {
        "success_only": True,
        "conversion_method": "state_projection_replay",
        "source": source.describe(),
        "exported_episodes": exported,
        "rejected_episodes": rejected,
        "rejected_count": len(rejected),
        "conversion_failures": failures,
        "conversion_failure_count": len(failures),
        "action_clipping": "recorded actions clipped to controller action-space bounds",
    }
    return episodes, provenance


def contract_state_dim(env) -> int:
    space = env.unwrapped.single_observation_space
    return int(np.prod(space.shape))


def probe_state_layout(env_state_dict_mode) -> dict:
    """Field -> [start, end) layout of the flattened state vector.

    Takes an env constructed with obs_mode="state_dict" (same task /
    controller / backend); ManiSkill's "state" obs is the ordered
    flattening of this dict.
    """
    obs, _ = env_state_dict_mode.reset(seed=0)
    layout: dict[str, list[int]] = {}
    cursor = 0

    def walk(d, prefix=""):
        nonlocal cursor
        for key, value in d.items():
            if isinstance(value, dict):
                walk(value, f"{prefix}{key}.")
            else:
                n = int(np.prod(value.shape[1:])) if value.ndim > 1 else 1
                layout[f"{prefix}{key}"] = [cursor, cursor + n]
                cursor += n

    walk(obs)
    return layout
